import { Proposal, Role } from './types';

export const mockProposals: Proposal[] = [
  {
    id: 'prop-001',
    courseName: 'Endocrinologia Ambulatorial',
    coordinator: 'Alano Matias',
    area: 'Saúde',
    subarea: 'Medicina',
    vertical: 'Pós-graduação',
    targetAudience: 'Médicos gerais e especialistas em formação',
    requestDate: '2023-10-01T10:00:00Z',
    currentPhase: 'Comitê',
    status: 'Em análise',
    observations: 'Projeto piloto focado em ambulatório',
    preCommitteeOpinion: 'Aprovado com ressalvas devido ao alto risco de canibalização.',
    maxSimilarity: 84.4,
    cannibalizationRisk: 'alto',
    priority: 'Alta',
    createdAt: '2023-10-01T10:00:00Z',
    updatedAt: '2023-10-15T14:30:00Z',
    similarCourses: [
      {
        id: 'sim-001',
        proposalId: 'prop-001',
        courseName: 'Endocrinologia',
        similarityPercent: 84.4,
        coordinator: 'Alano Matias',
        situation: 'Lançado',
        comment: 'Canibalização — o núcleo do tema já está ocupado por um curso amplo e forte. A diferenciação precisa estar na prática ambulatorial e no manejo longitudinal.',
        g2Id: '3627246',
        version: 'CV100',
        area: 'Saúde',
        workload: 480,
        relationType: 'canibalização'
      },
      {
        id: 'sim-002',
        proposalId: 'prop-001',
        courseName: 'Endocrinologia na Prática Médica',
        similarityPercent: 79.0,
        coordinator: 'Luiz Henrique Horta Hargreaves',
        situation: 'Em construção',
        comment: 'Canibalização — a aderência é muito alta e a proposta em cadastro já caminha na mesma direção.',
        g2Id: '3627576',
        version: 'CV100',
        area: 'Saúde',
        workload: 360,
        relationType: 'canibalização'
      },
      {
        id: 'sim-003',
        proposalId: 'prop-001',
        courseName: 'Medicina Metabólica: Diabetes e Obesidade',
        similarityPercent: 66.3,
        coordinator: 'Alano Matias',
        situation: 'Lançado',
        comment: 'Transversalidade — cobre parte relevante do ambulatório endócrino-metabólico, sobretudo em doenças prevalentes.',
        g2Id: '3627868',
        version: 'CV100',
        area: 'Saúde',
        workload: 400,
        relationType: 'transversalidade'
      }
    ]
  },
  {
    id: 'prop-002',
    courseName: 'Direito Digital e Proteção de Dados',
    coordinator: 'Mariana Silva',
    area: 'Direito',
    subarea: 'Tecnologia',
    vertical: 'Pós-graduação',
    targetAudience: 'Advogados, consultores jurídicos',
    requestDate: '2023-10-05T09:00:00Z',
    currentPhase: 'Aguardando Comitê',
    status: 'Em análise',
    observations: 'Alta demanda do mercado',
    preCommitteeOpinion: 'Aprovado, avançar para comitê',
    maxSimilarity: 45.2,
    cannibalizationRisk: 'baixo',
    priority: 'Normal',
    createdAt: '2023-10-05T09:00:00Z',
    updatedAt: '2023-10-12T11:00:00Z',
    similarCourses: [
       {
        id: 'sim-004',
        proposalId: 'prop-002',
        courseName: 'LGPD na Prática',
        similarityPercent: 45.2,
        coordinator: 'João Pedro',
        situation: 'Lançado',
        comment: 'Complementaridade — este novo abrange direito digital como um todo.',
        relationType: 'complementaridade'
      }
    ]
  },
  {
    id: 'prop-003',
    courseName: 'Gestão Ágil de Projetos',
    coordinator: 'Carlos Mendes',
    area: 'Negócios',
    subarea: 'Gestão',
    vertical: 'Extensão',
    requestDate: '2023-09-20T14:00:00Z',
    currentPhase: 'Reservas',
    status: 'Recebendo Proposta',
    maxSimilarity: 92.0,
    cannibalizationRisk: 'alto',
    priority: 'Normal',
    createdAt: '2023-09-20T14:00:00Z',
    updatedAt: '2023-09-21T09:00:00Z',
  },
  {
    id: 'prop-004',
    courseName: 'Engenharia de Prompt para IAs',
    coordinator: 'Ana Paula',
    area: 'Tecnologia',
    subarea: 'Inteligência Artificial',
    vertical: 'Graduação',
    requestDate: '2023-10-10T11:20:00Z',
    currentPhase: 'Solicitações',
    status: 'Em análise',
    maxSimilarity: 12.0,
    cannibalizationRisk: 'baixo',
    priority: 'Alta',
    createdAt: '2023-10-10T11:20:00Z',
    updatedAt: '2023-10-10T11:20:00Z',
  },
  {
    id: 'prop-005',
    courseName: 'Psicologia Organizacional',
    coordinator: 'Renato Lima',
    area: 'Saúde',
    subarea: 'Psicologia',
    vertical: 'Pós-graduação',
    requestDate: '2023-08-15T08:00:00Z',
    currentPhase: 'Propostas Aprovadas',
    status: 'Aprovado',
    finalDecision: 'Aprovado por unanimidade',
    maxSimilarity: 30.5,
    cannibalizationRisk: 'baixo',
    priority: 'Normal',
    createdAt: '2023-08-15T08:00:00Z',
    updatedAt: '2023-09-30T10:00:00Z',
  },
  {
    id: 'prop-006',
    courseName: 'MBA em Liderança Estratégica',
    coordinator: 'Carlos Mendes',
    area: 'Negócios',
    subarea: 'Liderança',
    vertical: 'MBA',
    requestDate: '2023-09-10T13:00:00Z',
    currentPhase: 'Stand By',
    status: 'Standby',
    preCommitteeOpinion: 'Rever ementa',
    maxSimilarity: 88.0,
    cannibalizationRisk: 'alto',
    priority: 'Normal',
    createdAt: '2023-09-10T13:00:00Z',
    updatedAt: '2023-10-05T16:00:00Z',
  },
  {
    id: 'prop-007',
    courseName: 'Marketing Digital Avançado',
    coordinator: 'Fernanda Costa',
    area: 'Comunicação',
    subarea: 'Marketing',
    vertical: 'Extensão',
    requestDate: '2023-07-20T09:30:00Z',
    currentPhase: 'Reprovados',
    status: 'Reprovado',
    finalOpinion: 'Já temos cursos idênticos não justifica novo lançamento.',
    maxSimilarity: 98.0,
    cannibalizationRisk: 'alto',
    priority: 'Baixa',
    createdAt: '2023-07-20T09:30:00Z',
    updatedAt: '2023-08-10T11:00:00Z',
  },
  {
    id: 'prop-008',
    courseName: 'Ciência de Dados em Finanças',
    coordinator: 'Ana Paula',
    area: 'Tecnologia',
    subarea: 'Data Science',
    vertical: 'Pós-graduação',
    requestDate: '2023-10-12T15:00:00Z',
    currentPhase: 'Pré-Comitê',
    status: 'Em análise',
    maxSimilarity: 65.0,
    cannibalizationRisk: 'médio',
    priority: 'Alta',
    createdAt: '2023-10-12T15:00:00Z',
    updatedAt: '2023-10-13T09:00:00Z',
    similarCourses: [
       {
        id: 'sim-005',
        proposalId: 'prop-008',
        courseName: 'MBA Analytics em Finanças',
        similarityPercent: 65.0,
        coordinator: 'Ana Paula',
        situation: 'Lançado',
        relationType: 'transversalidade'
      }
    ]
  },
  {
    id: 'prop-009',
    courseName: 'Enfermagem Estética Avançada',
    coordinator: 'Beatriz Almeida',
    area: 'Saúde',
    subarea: 'Enfermagem',
    vertical: 'Pós-graduação',
    requestDate: '2023-09-25T10:00:00Z',
    currentPhase: 'Aguardando aprovação',
    status: 'Em análise',
    maxSimilarity: 55.0,
    cannibalizationRisk: 'médio',
    priority: 'Normal',
    createdAt: '2023-09-25T10:00:00Z',
    updatedAt: '2023-09-26T14:00:00Z',
  },
  {
    id: 'prop-010',
    courseName: 'Educação Inclusiva',
    coordinator: 'Roberto Santos',
    area: 'Educação',
    subarea: 'Pedagogia',
    vertical: 'Pós-graduação',
    requestDate: '2023-10-09T08:45:00Z',
    currentPhase: 'Controle Interno',
    status: 'Em análise',
    maxSimilarity: 40.0,
    cannibalizationRisk: 'baixo',
    priority: 'Normal',
    createdAt: '2023-10-09T08:45:00Z',
    updatedAt: '2023-10-14T10:00:00Z',
  }
];
