import { YMedCourse, YMedProposal } from './ymed-types';

const UFS = ['SP', 'RJ', 'MG', 'BA', 'RS', 'PR', 'SC', 'GO', 'PE', 'CE', 'AM', 'PA', 'MT', 'MS', 'ES'];

function genMetrics(courseId: string) {
  return UFS.flatMap(uf =>
    [2024, 2025, 2026].flatMap(year =>
      Array.from({ length: 12 }, (_, i) => ({
        year,
        month: i + 1,
        uf,
        enrollments: Math.floor(Math.random() * 80) + 5,
        preEnrollments: Math.floor(Math.random() * 40) + 2,
        sales: Math.floor(Math.random() * 15000) + 800,
      }))
    )
  );
}

export const ymedCourses: YMedCourse[] = [
  {
    id: 'ymed-001',
    name: 'Medicina de Família e Comunidade',
    coordinator: 'INSBE',
    area: 'Clínica Médica',
    situation: 'Em Oferta',
    description: 'Curso voltado para a formação de médicos especialistas em atenção primária à saúde, com foco na medicina preventiva e na relação médico-paciente. Abrange desde consulta ambulatorial até acompanhamento longitudinal de famílias.',
    launchDate: '2022-03-15',
    disciplines: [
      { id: 'd1', name: 'Saúde da Família', workload: 60 },
      { id: 'd2', name: 'Epidemiologia Clínica', workload: 45 },
      { id: 'd3', name: 'Saúde Mental na APS', workload: 30 },
      { id: 'd4', name: 'Gestão em Saúde', workload: 30 },
    ],
    history: [
      { date: '2022-01-10', event: 'Proposta aprovada pelo comitê acadêmico.' },
      { date: '2022-03-15', event: 'Lançamento oficial do curso.' },
      { date: '2023-08-01', event: 'Atualização de grade curricular — inclusão de Saúde Mental na APS.' },
      { date: '2024-02-20', event: 'Curso atingiu 500 matrículas acumuladas.' },
    ],
    metrics: genMetrics('ymed-001'),
  },
  {
    id: 'ymed-002',
    name: 'Cardiologia Clínica',
    coordinator: 'Alano',
    area: 'Cardiologia',
    situation: 'Em Oferta',
    description: 'Especialização em cardiologia clínica com ênfase em diagnóstico por imagem, eletrocardiografia e manejo de insuficiência cardíaca. Curso altamente procurado por residentes de clínica médica.',
    launchDate: '2021-07-01',
    disciplines: [
      { id: 'd1', name: 'Eletrocardiografia Avançada', workload: 60 },
      { id: 'd2', name: 'Ecocardiografia Básica', workload: 45 },
      { id: 'd3', name: 'Insuficiência Cardíaca', workload: 45 },
      { id: 'd4', name: 'Farmacologia Cardiovascular', workload: 30 },
    ],
    history: [
      { date: '2021-05-01', event: 'Aprovação pelo comitê YMed.' },
      { date: '2021-07-01', event: 'Lançamento do curso.' },
      { date: '2022-11-10', event: 'Módulo de Ecocardiografia adicionado.' },
      { date: '2025-01-15', event: 'Renovação de parceria com Hospital Albert Einstein para casos clínicos.' },
    ],
    metrics: genMetrics('ymed-002'),
  },
  {
    id: 'ymed-003',
    name: 'Urgência e Emergência Médica',
    coordinator: 'ILHHH',
    area: 'Medicina de Urgência',
    situation: 'Em Oferta',
    description: 'Preparação completa para atuação em prontos-socorros e UTIs. Conteúdo prático com simulações clínicas, ACLS, ATLS e manejo de politrauma.',
    launchDate: '2020-09-01',
    disciplines: [
      { id: 'd1', name: 'Suporte Avançado de Vida (ACLS)', workload: 60 },
      { id: 'd2', name: 'Trauma e Politrauma (ATLS)', workload: 60 },
      { id: 'd3', name: 'Toxicologia Clínica', workload: 30 },
      { id: 'd4', name: 'Ventilação Mecânica', workload: 45 },
      { id: 'd5', name: 'Analgesia e Sedação', workload: 30 },
    ],
    history: [
      { date: '2020-07-15', event: 'Aprovação e início da produção de conteúdo.' },
      { date: '2020-09-01', event: 'Lançamento do curso.' },
      { date: '2023-04-01', event: 'Módulo de Toxicologia atualizado com novos protocolos.' },
    ],
    metrics: genMetrics('ymed-003'),
  },
  {
    id: 'ymed-004',
    name: 'Dermatologia para o Clínico',
    coordinator: 'IJR',
    area: 'Dermatologia',
    situation: 'Em Oferta',
    description: 'Curso focado no diagnóstico dermatológico para médicos não especialistas. Cobre as principais dermatoses, lesões suspeitas e manejo de urgências dermatológicas no consultório.',
    launchDate: '2023-02-14',
    disciplines: [
      { id: 'd1', name: 'Semiologia Dermatológica', workload: 45 },
      { id: 'd2', name: 'Dermatoses Inflamatórias', workload: 45 },
      { id: 'd3', name: 'Oncologia Cutânea', workload: 30 },
      { id: 'd4', name: 'Procedimentos Dermatológicos', workload: 30 },
    ],
    history: [
      { date: '2022-11-01', event: 'Aprovação do projeto pelo comitê.' },
      { date: '2023-02-14', event: 'Lançamento do curso.' },
      { date: '2024-06-01', event: 'Adição de atlas fotográfico interativo.' },
    ],
    metrics: genMetrics('ymed-004'),
  },
  {
    id: 'ymed-005',
    name: 'Neurologia Clínica Essencial',
    coordinator: 'INSBE',
    area: 'Neurologia',
    situation: 'Em Construção',
    description: 'Curso em desenvolvimento para capacitar médicos clínicos no reconhecimento e manejo inicial das principais doenças neurológicas: AVC, epilepsia, cefaleia e esclerose múltipla.',
    launchDate: '2026-09-01',
    disciplines: [
      { id: 'd1', name: 'Semiologia Neurológica', workload: 60 },
      { id: 'd2', name: 'AVC — Diagnóstico e Tratamento', workload: 45 },
      { id: 'd3', name: 'Epilepsia na Prática Clínica', workload: 30 },
    ],
    history: [
      { date: '2025-10-01', event: 'Proposta submetida ao comitê YMed.' },
      { date: '2025-11-15', event: 'Aprovação e início da fase de construção.' },
      { date: '2026-02-01', event: 'Produção de vídeos iniciada.' },
    ],
    metrics: genMetrics('ymed-005'),
  },
  {
    id: 'ymed-006',
    name: 'Endocrinologia e Diabetes',
    coordinator: 'Alano',
    area: 'Endocrinologia',
    situation: 'Em Oferta',
    description: 'Gestão do diabetes mellitus tipo 1 e tipo 2, tireoidopatias, obesidade e síndrome metabólica. Curso com foco em prática ambulatorial e prescrição racional.',
    launchDate: '2022-08-01',
    disciplines: [
      { id: 'd1', name: 'Diabetes Mellitus — Manejo Clínico', workload: 60 },
      { id: 'd2', name: 'Tireoidologia', workload: 45 },
      { id: 'd3', name: 'Obesidade e Síndrome Metabólica', workload: 45 },
      { id: 'd4', name: 'Hipertensão Arterial', workload: 30 },
    ],
    history: [
      { date: '2022-06-10', event: 'Aprovação do comitê.' },
      { date: '2022-08-01', event: 'Lançamento.' },
      { date: '2024-03-15', event: 'Atualização para incluir novos análogos de GLP-1.' },
    ],
    metrics: genMetrics('ymed-006'),
  },
  {
    id: 'ymed-007',
    name: 'Pediatria Ambulatorial',
    coordinator: 'ILHHH',
    area: 'Pediatria',
    situation: 'Em Oferta',
    description: 'Manejo das principais afecções pediátricas no ambulatório: infecções recorrentes, distúrbios do crescimento, imunizações e saúde do adolescente.',
    launchDate: '2021-03-01',
    disciplines: [
      { id: 'd1', name: 'Puericultura e Crescimento', workload: 45 },
      { id: 'd2', name: 'Infecções Pediátricas', workload: 45 },
      { id: 'd3', name: 'Calendário Vacinal Atualizado', workload: 30 },
      { id: 'd4', name: 'Saúde do Adolescente', workload: 30 },
    ],
    history: [
      { date: '2021-01-20', event: 'Aprovação.' },
      { date: '2021-03-01', event: 'Lançamento do curso.' },
      { date: '2025-02-01', event: 'Atualização do calendário vacinal conforme SBP 2025.' },
    ],
    metrics: genMetrics('ymed-007'),
  },
  {
    id: 'ymed-008',
    name: 'Ginecologia e Obstetrícia para Clínicos',
    coordinator: 'IJR',
    area: 'Ginecologia e Obstetrícia',
    situation: 'Em Cadastro',
    description: 'Curso em fase de cadastro no sistema acadêmico. Abordará o pré-natal de baixo risco, planejamento familiar, rastreamento de câncer ginecológico e urgências obstétricas.',
    launchDate: '2026-06-01',
    disciplines: [
      { id: 'd1', name: 'Pré-Natal de Baixo Risco', workload: 45 },
      { id: 'd2', name: 'Anticoncepção e Planejamento Familiar', workload: 30 },
      { id: 'd3', name: 'Rastreamento Oncológico Ginecológico', workload: 30 },
    ],
    history: [
      { date: '2025-09-01', event: 'Proposta aprovada.' },
      { date: '2026-01-10', event: 'Início do processo de cadastro no sistema.' },
    ],
    metrics: genMetrics('ymed-008'),
  },
  {
    id: 'ymed-009',
    name: 'Infectologia Clínica',
    coordinator: 'INSBE',
    area: 'Infectologia',
    situation: 'Em Oferta',
    description: 'Abordagem das principais doenças infecciosas prevalentes no Brasil: HIV/AIDS, hepatites virais, tuberculose, dengue e antimicrobianos na prática clínica.',
    launchDate: '2020-04-01',
    disciplines: [
      { id: 'd1', name: 'HIV e AIDS — Manejo Atual', workload: 45 },
      { id: 'd2', name: 'Tuberculose e Coinfecções', workload: 45 },
      { id: 'd3', name: 'Arboviroses Brasileiras', workload: 30 },
      { id: 'd4', name: 'Antimicrobianos Racionais', workload: 45 },
    ],
    history: [
      { date: '2020-02-01', event: 'Aprovação.' },
      { date: '2020-04-01', event: 'Lançamento.' },
      { date: '2023-07-01', event: 'Atualização com diretrizes do Ministério da Saúde 2023.' },
    ],
    metrics: genMetrics('ymed-009'),
  },
  {
    id: 'ymed-010',
    name: 'Reumatologia para o Generalista',
    coordinator: 'Alano',
    area: 'Reumatologia',
    situation: 'Suspenso',
    description: 'Diagnóstico e manejo das doenças reumatológicas mais comuns: lúpus, artrite reumatoide, fibromialgia e gota. Suspenso temporariamente para revisão de conteúdo.',
    launchDate: '2022-05-01',
    disciplines: [
      { id: 'd1', name: 'Artrite Reumatoide', workload: 45 },
      { id: 'd2', name: 'Lúpus Eritematoso Sistêmico', workload: 45 },
      { id: 'd3', name: 'Fibromialgia e Dor Crônica', workload: 30 },
    ],
    history: [
      { date: '2022-03-01', event: 'Aprovação e lançamento.' },
      { date: '2024-12-01', event: 'Curso suspenso para revisão e atualização de conteúdo.' },
    ],
    metrics: genMetrics('ymed-010'),
  },
  {
    id: 'ymed-011',
    name: 'Medicina do Trabalho',
    coordinator: 'ILHHH',
    area: 'Medicina do Trabalho',
    situation: 'Em Oferta',
    description: 'Capacitação em saúde ocupacional, perícias médicas, doenças relacionadas ao trabalho e legislação previdenciária. Voltado para médicos que atuam ou pretendem atuar em empresas.',
    launchDate: '2023-10-01',
    disciplines: [
      { id: 'd1', name: 'Saúde Ocupacional', workload: 60 },
      { id: 'd2', name: 'Perícia Médica', workload: 45 },
      { id: 'd3', name: 'Legislação Previdenciária', workload: 30 },
      { id: 'd4', name: 'Ergonomia e Doenças do Trabalho', workload: 30 },
    ],
    history: [
      { date: '2023-08-01', event: 'Aprovação.' },
      { date: '2023-10-01', event: 'Lançamento do curso.' },
    ],
    metrics: genMetrics('ymed-011'),
  },
  {
    id: 'ymed-012',
    name: 'Psiquiatria na Atenção Primária',
    coordinator: 'IJR',
    area: 'Psiquiatria',
    situation: 'Em Oferta',
    description: 'Identificação e manejo dos transtornos mentais mais prevalentes no contexto da APS: depressão, ansiedade, transtorno bipolar e dependência química.',
    launchDate: '2022-11-01',
    disciplines: [
      { id: 'd1', name: 'Depressão e Ansiedade na APS', workload: 45 },
      { id: 'd2', name: 'Transtorno Bipolar', workload: 30 },
      { id: 'd3', name: 'Dependência Química', workload: 30 },
      { id: 'd4', name: 'Psicofarmacologia Prática', workload: 45 },
    ],
    history: [
      { date: '2022-09-01', event: 'Aprovação pelo comitê.' },
      { date: '2022-11-01', event: 'Lançamento.' },
      { date: '2024-09-01', event: 'Atualização com novos antidepressivos aprovados pela Anvisa.' },
    ],
    metrics: genMetrics('ymed-012'),
  },
  {
    id: 'ymed-013',
    name: 'Ortopedia e Traumatologia Clínica',
    coordinator: 'INSBE',
    area: 'Ortopedia',
    situation: 'Descontinuado',
    description: 'Curso descontinuado por baixa adesão. Abordava diagnóstico e tratamento conservador das principais lesões ortopédicas.',
    launchDate: '2020-11-01',
    disciplines: [
      { id: 'd1', name: 'Fraturas e Luxações', workload: 45 },
      { id: 'd2', name: 'Lesões de Partes Moles', workload: 30 },
    ],
    history: [
      { date: '2020-09-01', event: 'Aprovação e lançamento.' },
      { date: '2023-01-01', event: 'Curso descontinuado por decisão estratégica.' },
    ],
    metrics: genMetrics('ymed-013'),
  },
  {
    id: 'ymed-014',
    name: 'Nefrologia para o Clínico',
    coordinator: 'Alano',
    area: 'Nefrologia',
    situation: 'Em Oferta',
    description: 'Abordagem das principais afecções renais: doença renal crônica, nefropatia diabética, litíase renal e uso racional de IECA/BRA na prática clínica.',
    launchDate: '2023-05-01',
    disciplines: [
      { id: 'd1', name: 'Doença Renal Crônica', workload: 60 },
      { id: 'd2', name: 'Nefropatia Diabética', workload: 45 },
      { id: 'd3', name: 'Litíase Renal', workload: 30 },
      { id: 'd4', name: 'Distúrbios Eletrolíticos', workload: 45 },
    ],
    history: [
      { date: '2023-03-01', event: 'Aprovação do comitê.' },
      { date: '2023-05-01', event: 'Lançamento.' },
    ],
    metrics: genMetrics('ymed-014'),
  },
  {
    id: 'ymed-015',
    name: 'Hematologia Clínica',
    coordinator: 'ILHHH',
    area: 'Hematologia',
    situation: 'Cancelado',
    description: 'Curso cancelado antes do lançamento por conflito de grade com outro produto do portfólio. Abordaria anemias, hemofilias e leucemias.',
    launchDate: '2025-01-01',
    disciplines: [
      { id: 'd1', name: 'Anemias — Diagnóstico Diferencial', workload: 45 },
      { id: 'd2', name: 'Hemofilias e Coagulopatias', workload: 30 },
    ],
    history: [
      { date: '2024-06-01', event: 'Proposta aprovada.' },
      { date: '2024-10-01', event: 'Curso cancelado por decisão estratégica de portfólio.' },
    ],
    metrics: genMetrics('ymed-015'),
  },
];

export const ymedProposals: YMedProposal[] = [
  {
    id: 'ymp-001',
    courseName: 'Oncologia Clínica para Médicos de Família',
    coordinator: 'INSBE',
    area: 'Oncologia',
    subarea: 'Rastreamento',
    requestDate: '2026-01-15',
    currentPhase: 'Revisão',
    status: 'Em análise',
    createdAt: '2026-01-15',
    updatedAt: '2026-02-01',
  },
  {
    id: 'ymp-002',
    courseName: 'Medicina Paliativa e Cuidados Paliativos',
    coordinator: 'Alano',
    area: 'Cuidados Paliativos',
    subarea: 'Dor Crônica',
    requestDate: '2026-02-10',
    currentPhase: 'Solicitações',
    status: 'Recebendo Proposta',
    createdAt: '2026-02-10',
    updatedAt: '2026-02-10',
  },
  {
    id: 'ymp-003',
    courseName: 'Pneumologia: DPOC e Asma',
    coordinator: 'ILHHH',
    area: 'Pneumologia',
    subarea: 'Doenças Obstrutivas',
    requestDate: '2025-11-20',
    currentPhase: 'Aguardando aprovação',
    status: 'Em análise',
    createdAt: '2025-11-20',
    updatedAt: '2026-01-10',
  },
  {
    id: 'ymp-004',
    courseName: 'Gastroenterologia Prática',
    coordinator: 'IJR',
    area: 'Gastroenterologia',
    subarea: 'Hepatologia',
    requestDate: '2025-12-05',
    currentPhase: 'Comitê',
    status: 'Em análise',
    createdAt: '2025-12-05',
    updatedAt: '2026-03-01',
  },
  {
    id: 'ymp-005',
    courseName: 'Oftalmologia para o Clínico',
    coordinator: 'INSBE',
    area: 'Oftalmologia',
    subarea: 'Emergências',
    requestDate: '2026-03-01',
    currentPhase: 'Solicitações',
    status: 'Recebendo Proposta',
    createdAt: '2026-03-01',
    updatedAt: '2026-03-01',
  },
  {
    id: 'ymp-006',
    courseName: 'Medicina Esportiva',
    coordinator: 'Alano',
    area: 'Medicina do Esporte',
    subarea: 'Lesões Musculoesqueléticas',
    requestDate: '2026-01-25',
    currentPhase: 'Propostas Aprovadas',
    status: 'Aprovado',
    createdAt: '2026-01-25',
    updatedAt: '2026-04-10',
  },
];
